In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
from sklearn.datasets import load_breast_cancer
bc = load_breast_cancer()
dir(bc)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [6]:
df = pd.DataFrame(bc["data"], columns= bc["feature_names"])
df["target"] = bc["target"]
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [9]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [10]:
df.corr()["target"]

mean radius               -0.730029
mean texture              -0.415185
mean perimeter            -0.742636
mean area                 -0.708984
mean smoothness           -0.358560
mean compactness          -0.596534
mean concavity            -0.696360
mean concave points       -0.776614
mean symmetry             -0.330499
mean fractal dimension     0.012838
radius error              -0.567134
texture error              0.008303
perimeter error           -0.556141
area error                -0.548236
smoothness error           0.067016
compactness error         -0.292999
concavity error           -0.253730
concave points error      -0.408042
symmetry error             0.006522
fractal dimension error   -0.077972
worst radius              -0.776454
worst texture             -0.456903
worst perimeter           -0.782914
worst area                -0.733825
worst smoothness          -0.421465
worst compactness         -0.590998
worst concavity           -0.659610
worst concave points      -0

#### Cek yang korelasinya lebih dari 0.5 atau kurang dari -0.5

In [12]:
df.corr()["target"][df.corr()["target"] >.5]

target    1.0
Name: target, dtype: float64

In [21]:
df.corr()["target"][df.corr()["target"] <-.5]

mean radius            -0.730029
mean perimeter         -0.742636
mean area              -0.708984
mean compactness       -0.596534
mean concavity         -0.696360
mean concave points    -0.776614
radius error           -0.567134
perimeter error        -0.556141
area error             -0.548236
worst radius           -0.776454
worst perimeter        -0.782914
worst area             -0.733825
worst compactness      -0.590998
worst concavity        -0.659610
worst concave points   -0.793566
Name: target, dtype: float64

In [23]:
i = np.array(df.corr()["target"][df.corr()["target"] <-.5].index)
dfNew = df[i]
dfNew["target"] = df["target"]
dfNew

<ipython-input-23-2aef0c10f436>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfNew["target"] = df["target"]


mean radius  mean perimeter  mean area  mean compactness  mean concavity  \
0          17.99          122.80     1001.0           0.27760         0.30010   
1          20.57          132.90     1326.0           0.07864         0.08690   
2          19.69          130.00     1203.0           0.15990         0.19740   
3          11.42           77.58      386.1           0.28390         0.24140   
4          20.29          135.10     1297.0           0.13280         0.19800   
..           ...             ...        ...               ...             ...   
564        21.56          142.00     1479.0           0.11590         0.24390   
565        20.13          131.20     1261.0           0.10340         0.14400   
566        16.60          108.30      858.1           0.10230         0.09251   
567        20.60          140.10     1265.0           0.27700         0.35140   
568         7.76           47.92      181.0           0.04362         0.00000   

     mean concave points  radius error  perimeter error  area error  \
0                0.14710        1.0950            8.589      153.40   
1                0.07017        0.5435            3.398       74.08   
2                0.12790        0.7456            4.585       94.03   
3                0.10520        0.4956            3.445       27.23   
4                0.10430        0.7572            5.438       94.44   
..                   ...           ...              ...         ...   
564              0.13890        1.1760            7.673      158.70   
565              0.09791        0.7655            5.203       99.04   
566              0.05302        0.4564            3.425       48.55   
567              0.15200        0.7260            5.772       86.22   
568              0.00000        0.3857            2.548       19.15   

     worst radius  worst perimeter  worst area  worst compactness  \
0          25.380           184.60      2019.0            0.66560   
1          24.990           158.80      1956.0            0.18660   
2          23.570           152.50      1709.0            0.42450   
3          14.910            98.87       567.7            0.86630   
4          22.540           152.20      1575.0            0.20500   
..            ...              ...         ...                ...   
564        25.450           166.10      2027.0            0.21130   
565        23.690           155.00      1731.0            0.19220   
566        18.980           126.70      1124.0            0.30940   
567        25.740           184.60      1821.0            0.86810   
568         9.456            59.16       268.6            0.06444   

     worst concavity  worst concave points  target  
0             0.7119                0.2654       0  
1             0.2416                0.1860       0  
2             0.4504                0.2430       0  
3             0.6869                0.2575       0  
4             0.4000                0.1625       0  
..               ...                   ...     ...  
564           0.4107                0.2216       0  
565           0.3215                0.1628       0  
566           0.3403                0.1418       0  
567           0.9387                0.2650       0  
568           0.0000                0.0000       1  

[569 rows x 16 columns]

### Standard Scalling

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
stds = StandardScaler()
dataSTD = stds.fit_transform(dfNew.iloc[:,:-1]) #exclude target
dataSTD

array([[ 1.09706398,  1.26993369,  0.9843749 , ...,  2.61666502,
         2.10952635,  2.29607613],
       [ 1.82982061,  1.68595471,  1.90870825, ..., -0.43044422,
        -0.14674897,  1.0870843 ],
       [ 1.57988811,  1.56650313,  1.55888363, ...,  1.08293217,
         0.85497394,  1.95500035],
       ...,
       [ 0.70228425,  0.67267578,  0.57795264, ...,  0.35073535,
         0.3267666 ,  0.41406869],
       [ 1.83834103,  1.98252415,  1.73521799, ...,  3.90484795,
         3.19760468,  2.28998549],
       [-1.80840125, -1.81438851, -1.34778924, ..., -1.2075525 ,
        -1.30583065, -1.74506282]])

#### Cek & Drop Outliers

In [45]:
dfZ = pd.DataFrame(dataSTD)
dfZ["target"] = dfNew["target"]
dfZ

0         1         2         3         4         5         6  \
0    1.097064  1.269934  0.984375       NaN       NaN       NaN  2.489734   
1    1.829821  1.685955  1.908708 -0.487072 -0.023846  0.548144  0.499255   
2    1.579888  1.566503  1.558884  1.052926  1.363478  2.037231  1.228676   
3   -0.768909 -0.592687 -0.764464       NaN  1.915897  1.451707  0.326373   
4    1.750297  1.776573  1.826229  0.539340  1.371011  1.428493  1.270543   
..        ...       ...       ...       ...       ...       ...       ...   
564  2.110995  2.060786  2.343856  0.219060  1.947285  2.320965       NaN   
565  1.704854  1.615931  1.723842 -0.017833  0.693043  1.263669  1.300499   
566  0.702284  0.672676  0.577953 -0.038680  0.046588  0.105777  0.184892   
567  1.838341  1.982524  1.735218       NaN       NaN       NaN  1.157935   
568 -1.808401 -1.814389 -1.347789 -1.150752 -1.114873 -1.261820 -0.070279   

            7         8         9        10        11        12        13  \
0         NaN  2.487578  1.886690  2.303601  2.001237       NaN  2.109526   
1    0.263327  0.742402  1.805927  1.535126  1.890489 -0.430444 -0.146749   
2    0.850928  1.181336  1.511870  1.347475  1.456285  1.082932  0.854974   
3    0.286593 -0.288378 -0.281464 -0.249939 -0.550021       NaN  1.989588   
4    1.273189  1.190357  1.298575  1.338539  1.220724 -0.313395  0.613179   
..        ...       ...       ...       ...       ...       ...       ...   
564  2.379583       NaN  1.901185  1.752563  2.015301 -0.273318  0.664512   
565  1.156857  1.291565  1.536720  1.421940  1.494959 -0.394820  0.236573   
566  0.276693  0.180698  0.561361  0.579001  0.427906  0.350735  0.326767   
567  1.438530  1.009503  1.961239  2.303601  1.653171       NaN       NaN   
568 -0.157449 -0.466152 -1.410893 -1.432735 -1.075813 -1.207552 -1.305831   

           14  target  
0    2.296076       0  
1    1.087084       0  
2    1.955000       0  
3    2.175786       0  
4    0.729259       0  
..        ...     ...  
564  1.629151       0  
565  0.733827       0  
566  0.414069       0  
567  2.289985       0  
568 -1.745063       1  

[569 rows x 16 columns]

In [46]:
dfZ[(dfZ > 2.5) | (dfZ < -2.5)] = np.NaN
dfZ = dfZ.dropna()
dfZ

0         1         2         3         4         5         6  \
1    1.829821  1.685955  1.908708 -0.487072 -0.023846  0.548144  0.499255   
2    1.579888  1.566503  1.558884  1.052926  1.363478  2.037231  1.228676   
4    1.750297  1.776573  1.826229  0.539340  1.371011  1.428493  1.270543   
5   -0.476375 -0.387148 -0.505650  1.244335  0.866302  0.824656 -0.255070   
6    1.170908  1.138125  1.095295  0.088295  0.300072  0.646935  0.149883   
..        ...       ...       ...       ...       ...       ...       ...   
560 -0.021952 -0.024262 -0.154973  0.156521 -0.554670 -0.151647 -0.146794   
561 -0.831392 -0.877311 -0.764748 -1.303122 -1.114873 -1.261820 -0.328698   
565  1.704854  1.615931  1.723842 -0.017833  0.693043  1.263669  1.300499   
566  0.702284  0.672676  0.577953 -0.038680  0.046588  0.105777  0.184892   
568 -1.808401 -1.814389 -1.347789 -1.150752 -1.114873 -1.261820 -0.070279   

            7         8         9        10        11        12        13  \
1    0.263327  0.742402  1.805927  1.535126  1.890489 -0.430444 -0.146749   
2    0.850928  1.181336  1.511870  1.347475  1.456285  1.082932  0.854974   
4    1.273189  1.190357  1.298575  1.338539  1.220724 -0.313395  0.613179   
5   -0.321304 -0.289258 -0.165498 -0.115009 -0.244320  1.721616  1.263243   
6    0.155410  0.298627  1.368983  1.368325  1.275220  0.021215  0.509552   
..        ...       ...       ...       ...       ...       ...       ...   
560  0.010861 -0.230954 -0.200702 -0.210324 -0.305671 -0.177261 -0.669679   
561 -0.408430 -0.385626 -0.900641 -0.955268 -0.775210 -1.267986 -1.305831   
565  1.156857  1.291565  1.536720  1.421940  1.494959 -0.394820  0.236573   
566  0.276693  0.180698  0.561361  0.579001  0.427906  0.350735  0.326767   
568 -0.157449 -0.466152 -1.410893 -1.432735 -1.075813 -1.207552 -1.305831   

           14  target  
1    1.087084       0  
2    1.955000       0  
4    0.729259       0  
5    0.905888       0  
6    1.196716       0  
..        ...     ...  
560 -0.149315       1  
561 -1.745063       1  
565  0.733827       0  
566  0.414069       0  
568 -1.745063       1  

[516 rows x 16 columns]

In [47]:
dataSTD2 = np.array(dfZ.iloc[:,:-1])
dataSTD2

array([[ 1.82982061,  1.68595471,  1.90870825, ..., -0.43044422,
        -0.14674897,  1.0870843 ],
       [ 1.57988811,  1.56650313,  1.55888363, ...,  1.08293217,
         0.85497394,  1.95500035],
       [ 1.75029663,  1.77657315,  1.82622928, ..., -0.31339451,
         0.61317876,  0.72925926],
       ...,
       [ 1.70485436,  1.61593137,  1.72384158, ..., -0.39482039,
         0.23657316,  0.73382724],
       [ 0.70228425,  0.67267578,  0.57795264, ...,  0.35073535,
         0.3267666 ,  0.41406869],
       [-1.80840125, -1.81438851, -1.34778924, ..., -1.2075525 ,
        -1.30583065, -1.74506282]])

### PCA

In [26]:
from sklearn import decomposition

In [48]:
pca = decomposition.PCA(n_components= 3)

datapca = pca.fit_transform(dataSTD2)
datapca

array([[ 4.24293416, -2.66952123, -0.86054826],
       [ 6.05784874, -0.07449058,  0.34729866],
       [ 5.18481091, -1.47442066,  0.76067209],
       ...,
       [ 4.81418581, -2.12751465,  0.62725377],
       [ 2.0952615 , -0.42412575, -0.2471231 ],
       [-4.08488355, -0.20752418,  1.34964945]])

In [49]:
pca.explained_variance_ratio_

array([0.7473689 , 0.14043917, 0.06210436])

### Pipeline : StandardScaller & PCA

In [33]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(StandardScaler(), decomposition.PCA(n_components= 3))
datapipe = pipe.fit_transform(dfNew.iloc[:,:-1])
datapipe

array([[ 8.29601665, -1.61286602,  2.2463328 ],
       [ 3.55115547,  2.17862573, -2.03780651],
       [ 5.39482874, -0.12497657, -0.39645918],
       ...,
       [ 1.42239809,  0.27925871, -0.58030947],
       [ 8.50580823, -3.52892547,  0.01392803],
       [-4.54608267,  0.86126225,  1.56044555]])

#### Inverse ke value semula

In [34]:
pipe.inverse_transform(datapipe)[0]

array([1.89361465e+01, 1.29256168e+02, 1.18788294e+03, 2.60684046e-01,
       3.21696506e-01, 1.48732685e-01, 1.13852282e+00, 8.48284503e+00,
       1.49727446e+02, 2.37476708e+01, 1.65455426e+02, 1.80523551e+03,
       6.34443510e-01, 7.90349764e-01, 2.67061632e-01])

<hr>

### Splitting Datasets

In [50]:
x = datapca
y = np.array(dfZ["target"])

x.shape, y.shape

((516, 3), (516,))

In [51]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x, y, test_size= .15)

xtr.shape, xts.shape

((438, 3), (78, 3))

### K-Nearest Neighbors

In [52]:
from sklearn.neighbors import KNeighborsClassifier
k = round(xtr.shape[0] ** .5)
k

21

In [53]:
modKNN = KNeighborsClassifier(n_neighbors= k)
modKNN.fit(xtr, ytr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=21, p=2,
                     weights='uniform')

In [55]:
from sklearn.metrics import classification_report
print(classification_report(yts, modKNN.predict(xts)))

              precision    recall  f1-score   support

           0       0.95      0.70      0.81        27
           1       0.86      0.98      0.92        51

    accuracy                           0.88        78
   macro avg       0.91      0.84      0.86        78
weighted avg       0.89      0.88      0.88        78



In [56]:
modKNN.score(xts, yts)

0.8846153846153846